### ISSUE TITLE
Fix Contact icons and images

### ISSUE THREAD

**Issue by Moutasim02** [SpecialProjectADU/Site#38]
Check Contact.html src linking for images.

**Comment by Moutasim02** [comment]
![image](https://github.com/SpecialProjectADU/Site/assets/23410040/158bed84-47d7-4684-97d9-ef2573aad9fb)
The logo image is not showing up.
+ We might need a better overall UI enhancement of the page (Maybe something like cards for each block) (Not Mandatory Unless all bugs are solved)

**Comment by rahaf2201** [comment]
Fixed!
![image](https://github.com/SpecialProjectADU/Site/assets/73061653/44ad4a50-dfd2-472e-a89c-b68d07509ba9)

**Comment by rahaf2201** [comment]
I zoomed out to show almost the whole page but the original shouldn't have the white border spaces from the right & left as the image shows above.

**Comment by binHarby** [comment]
@rahaf2201  the image of sheik zayed is not showing because you guys didn't add it to the `images` folder. Make a new branch with the that image included. 

it should be `images/azD0BCjz-Sheikh-Zayed-15.jpg` like the code you have. 

Also, might as well change the 'Contact Us' title text to a color other than white (its not showing)

**Comment by rahaf2201** [comment]
Done! I have uploaded all missing images of my group's pages in the images folder with the branch name "Rahaf 2".
